# **Class 21: 24th July 2022: Pandas Library**

Datastax server not up and running. Hence we are doing Pandas Library instead of Cassandra. Cassandra (Document Database: CQL Cassandra Query Language) is similar to MongoDB

Pandas Library is used for Data Manipulation/Aggregation purposes

Dataset Link: https://drive.google.com/drive/folders/1vdLTTFQczfXW5o__f1ce5WfDqfI5JYAF?usp=sharing

We will be using Jupyter Notebook because here we can visualize data intuitively whereas we can't in Pycharm

In [1]:
#Importing Pandas Library
import pandas as pd

In [7]:
#Reading the Excel File Attribute Dataset.xlsx
attribute_data = pd.read_excel(r'/content/sample_data/Attribute DataSet.xlsx')
attribute_data

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [8]:
type(attribute_data) #DataFrame

#Series is similar to list but not same

pandas.core.frame.DataFrame

In [ ]:
#Reading data from different Sheet than Sheet 1 using sheet_name parameter in pandas
sheet2_data = pd.read_excel(r'File Name.xlsx',sheet_name = 'Sheet2')
sheet2_data_v1 = pd.read_excel(r'File Name.xlsx',sheet_name = 'Sheet2', header = None) #Will not treat first record as column header. By default we get Row index and Column Index in Pandas Dataframe
#If we dont want numbers in row and column header, then we can use argument names as shown below
sheet2_data_v2 = pd.read_excel(r'File Name.xlsx',sheet_name = 'Sheet2', header = None, names = ['A','B','C','D','E','F','G','H'])

In [9]:
attribute_data

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [11]:
attribute_data.head(2) #Will show first 2 records

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [12]:
attribute_data.head() #Will show first 5 records

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [13]:
attribute_data.tail(2) #Will show last 2 records

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [14]:
attribute_data.tail() #Will show last 5 records

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [16]:
#Reading csv File
haberman_data = pd.read_csv(r'/content/sample_data/haberman.csv')
haberman_data

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [18]:
#The above data does not contain header
haberman_data_v1 = pd.read_csv(r'/content/sample_data/haberman.csv', header = None, names = ["Age","Patient's year of Operation", "Number of Positive","Survival Status"])
haberman_data_v1

     Age  Patient's year of Operation  Number of Positive  Survival Status
0     30                           64                   1                1
1     30                           62                   3                1
2     30                           65                   0                1
3     31                           59                   2                1
4     31                           65                   4                1
..   ...                          ...                 ...              ...
301   75                           62                   1                1
302   76                           67                   0                1
303   77                           65                   3                1
304   78                           65                   1                2
305   83                           58                   2                2

[306 rows x 4 columns]

In [20]:
#We have taken a csv file and then replace comma delimiter with @ symbol. Now we want to read the data
haberman_data_v2 = pd.read_csv('/content/sample_data/haberman_v1.csv')
haberman_data_v2 #Not able to separate the data because comma is delimiter and it is not present in the data

      30@64@1@1
0     30@62@3@1
1     30@65@0@1
2     31@59@2@1
3     31@65@4@1
4    33@58@10@1
..          ...
300   75@62@1@1
301   76@67@0@1
302   77@65@3@1
303   78@65@1@2
304   83@58@2@2

[305 rows x 1 columns]

In [21]:
#To fix above, we will use separator argument in pandas
haberman_data_v3 = pd.read_csv('/content/sample_data/haberman_v1.csv', sep = '@')
haberman_data_v3

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [23]:
#Getting Data from Github: Go to Raw option and then get the link. This raw option will not be available for every type of format
github_data = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv')
github_data

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [24]:
#Extracting Tabular Data from website: https://www.basketball-reference.com/leagues/NBA_2015_totals.html 
nba = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html') 
nba

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [25]:
type(nba) #List

list

In [27]:
len(nba) #This tells us the number of tables present in the list nba. We have one table

1

In [29]:
nba[0]  #Accessing data from list nba

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [30]:
#Reading json (Java Script Object Notation) format: Combination of Dictionaries: We can use json viewer online to understand json in better way
#Keys become our column Names and Row becomes our values of those keys 
json_data = pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')
json_data

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47834,1315766705,PR_kwDOAA0YD847_P6c,47834,DEPR: inplace keyword for Categorical.set_orde...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47833,1315747437,PR_kwDOAA0YD847_MdV,47833,DOC: added type annotations and tests to check...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #47829 \r\n- [x] Added [type anno...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47832,1315745290,I_kwDOAA0YD85ObK4K,47832,BUG: Out of bound dates can be saved to feathe...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47831,1315742847,PR_kwDOAA0YD847_LmP,47831,TYP: pandas/io annotations from pandas-stubs,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Copied annotations from pandas-stubs when pand...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47830,1315736481,I_kwDOAA0YD85ObIuh,47830,DOC: repurpose `Styler` as a general display t...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47829,1315627196,I_kwDOAA0YD85OauC8,47829,DOC: clarify that assert_produces_warning can ...,...,NaT,MEMBER,NaN,NaN,NaN,Noticed in https://github.com/pandas-dev/panda...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47828,1315602520,PR_kwDOAA0YD847-xLx,47828,WIP warn if parsing with du_parse,...,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #12585 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47827,1315518998,PR_kwDOAA0YD847-gxJ,47827,TYP: pandas/plotting annotations from pandas-s...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Copied annotations from pandas-stubs when pand...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47826,1315489169,PR_kwDOAA0YD847-azR,47826,REF: de-duplicate PeriodArray arithmetic code,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,and improved exception message\r\n\r\n- [ ] cl...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47825,1315366529,PR_kwDOAA0YD847-Au9,47825,Specify that both ``by`` and ``level`` should ...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47823,1315356638,I_kwDOAA0YD85OZr_e,47823,CI/TST: Avoid xfail(strict=False) in test_roun...,...,NaT,MEMBER,NaN,NaN,NaN,Patched in https://github.com/pandas-dev/panda...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47821,1315176452,PR_kwDOAA0YD8479X5p,47821,Fixed metadata propagation in Dataframe.idxmax...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,â€¦28283\r\n\r\n- [x] contributes to #28283 cal...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47820,1314912497,I_kwDOAA0YD85OX_jx,47820,"Developement environment with docker ""pandas 0...",...,NaT,NONE,NaN,NaN,NaN,### Installation check\n\n- [X] I have read th...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47819,1314421895,I_kwDOAA0YD85OWHyH,47819,ENH: Add `axis` parameter to `add_prefix` and ...,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47818,1314160371,PR_kwDOAA0YD8475z54,47818,ENH: Add ArrowDype and .array.ArrowExtensionDt...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47817,1313384076,PR_kwDOAA0YD8473I1n,47817,CI/TYP: run stubtest,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Stubtest enforces that pyi files do not get ou...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47816,1313330637,PR_kwDOAA0YD84729MS,47816,TST: Addition test for get_indexer for interva...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #30178 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47815,1312963662,I_kwDOAA0YD85OQjxO,47815,ENH:,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\r\n\r\n- [ ] Adding new funct...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47813,1312816808,I_kwDOAA0YD85OP_6o,47813,DOC: Add example of drop_duplicates dropping a...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47812,1312398584,I_kwDOAA0YD85OOZz4,47812,BUG: DataFrame.join with categorical index res...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47811,1312245690,PR_kwDOAA0YD847zJtQ,47811,ENH/TST: Add argsort/min/max for ArrowExtensio...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47808,1312172833,PR_kwDOAA0YD847y5L7,47808,DOC: add pivot_table note to dropna doc,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #47447 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47806,1311959095,PR_kwDOAA0YD847yIFN,47806,CI/TYP: bump mypy and pyright,...,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,No type changes this time (but there will be a...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47801,1311338441,PR_kwDOAA0YD847v7FS,47801,TST: Test series construct of dtype timedelta6...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #35465 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47799,1311055934,I_kwDOAA0YD85OJSA-,47799,DOC: iloc docs should indicate a tuple is valid,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47796,1310483335,PR_kwDOAA0YD847s9Pu,47796,DEPS: drop np19 support,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47794,1310212439,PR_kwDOAA0YD847sBrd,47794,BUG: fixed OutOfBoundsDatetime exception when ...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #45319\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47793,1310209703,PR_kwDOAA0YD847sBGk,47793,TST: test for inconsistency due to dtype=strin...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46512\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47791,1309754901,I_kwDOAA0YD85OEUYV,47791,BUG: failed to use slice(None) in list of labe...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47790,1309414216,I_kwDOAA0YD85ODBNI,47790,# DEV: Gitpod integration,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,"We would like to introduce gitpod integration,...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [31]:
json_data.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app', 'state_reason'],
      dtype='object')

In [32]:
json_data['user']

0     {'login': 'jbrockmendel', 'id': 8078968, 'node...
1     {'login': 'shourya5', 'id': 73142986, 'node_id...
2     {'login': 'adrienpacifico', 'id': 6614121, 'no...
3     {'login': 'twoertwein', 'id': 6618166, 'node_i...
4     {'login': 'attack68', 'id': 24256554, 'node_id...
5     {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
6     {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
7     {'login': 'twoertwein', 'id': 6618166, 'node_i...
8     {'login': 'jbrockmendel', 'id': 8078968, 'node...
9     {'login': 'GivyBoy', 'id': 58392771, 'node_id'...
10    {'login': 'mroeschke', 'id': 10647082, 'node_i...
11    {'login': 'SomtochiUmeh', 'id': 74836691, 'nod...
12    {'login': 'adrienpacifico', 'id': 6614121, 'no...
13    {'login': 'Brinkhuis', 'id': 3044985, 'node_id...
14    {'login': 'mroeschke', 'id': 10647082, 'node_i...
15    {'login': 'twoertwein', 'id': 6618166, 'node_i...
16    {'login': 'parthi-siva', 'id': 25401444, 'node...
17    {'login': 'GeorgePearse', 'id': 47161914, 'nod...
18    {'login': 'smarie', 'id': 3236794, 'node_id': ...
19    {'login': 'daviskirk', 'id': 1049817, 'node_id...
20    {'login': 'mroeschke', 'id': 10647082, 'node_i...
21    {'login': 'Mehgarg', 'id': 65103188, 'node_id'...
22    {'login': 'twoertwein', 'id': 6618166, 'node_i...
23    {'login': 'Th3nn3ss', 'id': 25160953, 'node_id...
24    {'login': 'Dr-Irv', 'id': 15113894, 'node_id':...
25    {'login': 'fangchenli', 'id': 7614606, 'node_i...
26    {'login': 'srotondo', 'id': 97266896, 'node_id...
27    {'login': 'Shadimrad', 'id': 93452403, 'node_i...
28    {'login': 'Ynjxsjmh', 'id': 40143136, 'node_id...
29    {'login': 'noatamir', 'id': 6564007, 'node_id'...
Name: user, dtype: object

In [33]:
#Unwrapping dictionary of dictionary
json_data['user'][0]

{'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
 'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
 'gravatar_id': '',
 'html_url': 'https://github.com/jbrockmendel',
 'id': 8078968,
 'login': 'jbrockmendel',
 'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
 'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
 'site_admin': False,
 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
 'type': 'User',
 'url': 'https://api.github.com/users/jbrockmendel'}

In [36]:
#Converting dataframe into json
attribute_data.to_json('Attribute Data_JSON')

In [ ]:
#pwd #Present Working Directory
#Spark Dataframe is faster than Pandas Dataframe because it uses optimizer internally.

In [41]:
#Saving Data in form of csv,excel etc
attribute_data.to_csv("CSV Attribute Data.csv") #Give the relevant path with filename if we dont want to store in present working directory
attribute_data.to_json("JSON Attribute Data.json")
attribute_data.to_excel("Excel Attribute Data.xlsx")
attribute_data.to_csv("Attribute Data1.csv",sep = '@') #If we want to change the delimiter, we can use separator parameter
attribute_data.to_csv("Attribute Data2.csv",sep = '#')
attribute_data.to_csv("Attribute Data3.csv",sep = '#', index = False) #Row Index will be removed from our saved file

#**TASK**

We have Attribute Dataset  and Dress Sales Dataset. These are connected to each other based on Dress_ID. Perform the Following Task:


1. Create a Table of attribute dataset and dress dataset in mysql workbench/python
2. Do a bulk load for these 2 tables for respective dataset in mysql workbench/python
3. Read these datasets in pandas as a dataframe
4. Convert Attribute Dataset in JSON Format (.to_json will be used)
5. Store this json dataset into mongodb (Insert_many will be used)
6. In SQL task, try to perform left join operation with Attribute dataset and dress dataset on column Dress_ID
7. Write the SQL query to find out how many unique dress that we have based on Dress_ID
8. Try to find out how many dress is having recommendation as 0
9. Try to find out total dress sales for each and every Dress_ID
10. Try to find out the third highest most selling Dress_ID